---
title: "Project2"
author: "Group 3"
date: "7/9/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project 2

```{r}
library(utils) # Need to add to any data read in
library(psych)
library(kableExtra)
library(tidyverse)
library(corrplot)
library(MASS)
library(forecast)
library(caret)
ph <- read.csv(
  "https://raw.githubusercontent.com/palmorezm/msds/main/624/Projects/Project2/StudentData%20-%20TO%20MODEL.csv")
```


```{r}
ph.desc <- describe(ph)
kable(t(ph.desc))
```



```{r}
plot(ph$PH)
numerics <- ph %>% 
  dplyr::select(is.numeric) 
res <- cor(numerics, use = "complete.obs")
round(res, 2)
corrplot::corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
numerics[is.na(numerics)] <- median(numerics, na.rm=TRUE)
ph %>% 
  select(PH, Oxygen.Filler) %>% 
  mutate(ValueIndex = 1:length(ph$PH)) %>% 
  ggplot() + 
  geom_point(aes(ValueIndex, PH, color = Oxygen.Filler))
ggplot(ph, aes(PH)) + geom_histogram() 
```




```{r}
ggplot() + geom_boxplot(aes(ph$PH))
```



```{r}
# replaces NA with median (given a removal of missing values in calculation)
for (i in colnames(ph)) {
  ph[[i]][is.na(ph[[i]])] <- median(ph[[i]], na.rm=TRUE)
}
sum(is.na(ph))
```



```{r}
# select numeric variables
ph.numerics <- ph %>% 
  dplyr::select(is.numeric)
# remove outliers based on IQR
for (i in colnames(ph.numerics)) {
  iqr <- IQR(ph.numerics[[i]])
  q <- quantile(ph.numerics[[i]], probs = c(0.25, 0.75), na.rm = FALSE)
  qupper <- q[2]+1.5*iqr
  qlower <- q[1]+1.5*iqr
  outlier_free <- subset(ph.numerics, ph.numerics[[i]] > (q[1] - 1.5*iqr) & ph.numerics[[i]] < (q[2]+1.5*iqr) )
}
ph.numerics <- outlier_free
# join outlier free numerics with categorical 
Brand.Code <- ph$ï..Brand.Code
df <- cbind(Brand.Code, ph.numerics)
sum(is.na(df$Brand.Code))
```




```{r}
model.pm <- lm(PH~.,df)
pm <- stepAIC(model.pm, trace = F, direction = "both")
p <- summary(pm)$call
pm <- lm(p[2], df)
summary(pm)
```



```{r}
model.ks <- lm(PH~., df)
summary(model.ks)
```




```{r}
data <- df %>% 
  dplyr::select(Brand.Code, 
                Carb.Volume,
                Fill.Ounces,
                PC.Volume,
                Carb.Temp,
                PSC, 
                PSC.Fill, 
                PSC.CO2,
                PH,
                Mnf.Flow, 
                Carb.Pressure1, 
                Fill.Pressure, 
                Hyd.Pressure2, 
                Hyd.Pressure3, 
                Filler.Level,
                Temperature, 
                Usage.cont,
                Carb.Flow,
                Density,
                Balling,
                Pressure.Vacuum, 
                Oxygen.Filler, 
                Bowl.Setpoint, 
                Pressure.Setpoint, 
                Alch.Rel,
                Balling.Lvl)
```


```{r}
# Split 70-30 training test
set.seed(1102)
index <- createDataPartition(data$PH, p = .7, 
                             list = FALSE, times = 1)
train <- data[index,]
test <- data[-index,]
```







## Model Building and Evaluation (Chunjie)










































































