---
title: "HW14"
author: "Zachary Palmore"
date: "5/6/2021"
output: pdf_document
subtitle: "FUNDAMENTALS OF COMPUTATIONAL MATHEMATICS"
header-includes: 
- \newcommand{\bcenter}{\begin{center}}
- \newcommand{\ecenter}{\end{center}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\bcenter 

## Prompt 

\ecenter

This week, we'll work out some Taylor Series expansions of popular functions. For each function, only consider its valid ranges as indicated in the notes when you are computing the Taylor Series expansion. Please submit your assignment as a R-Markdown document.

The functions include: 


$$^{1} \hspace{8pt} f(x) = \frac{1}{(1-x)}$$


$$^{2} \hspace{8pt} f(x) = e^x$$


$$^{3} \hspace{8pt} f(x) = \ln(1+x)$$



\bcenter 

## Response 

\ecenter

Given the Maclaruin Series (Taylor series set to 0):

$$\sum^{\infty}_{n = 0}\frac{f^{(n)}(a)}{n!}(x-a)^n$$

We can solve

## Function 1

|Derivatives                         | Solved Maclaurin Series |
|------------------------------------|-------------------------|
| $\ f(x) = \frac{1}{1-x}$           |f(0) = 1                 |
|------------------------------------|-------------------------|
| $\ f'(x) = \frac{1}{(1-x)^2}$      |f(0) = 1                 |
|------------------------------------|-------------------------|
| $\ f''(x) = -\frac{2}{(1-x)^3}$    |f(0) = 2                 |
|------------------------------------|-------------------------|
| $\ f'''(x) = \frac{6}{(1-x)^4}$    |f(0) = 6                 | 
|------------------------------------|-------------------------|
| $\ f^{4}(x) = -\frac{24}{(1-x)^5}$ |f(0) = 24                |
|------------------------------------|-------------------------|
| $\ f^{5}(x) = -\frac{120}{(1-x)^6}$|f(0) = 120               |
|------------------------------------|-------------------------|

Plug in:
$$\sum^{\infty}_{n = 0} \frac{f^{(n)}*(0)}{n!}(x)^n$$
$$1 + \frac{1}{1!}x + \frac{2}{2!}x^{2}+ \frac{6}{3!}x^{3} + \frac{24}{4!}x^{4} + \frac{120}{5!}x^{5}$$
$$f(x) = 1 + x + x^2 + x^3 + x^4 ...$$

Our result using Taylor series:
$$f(x) = \frac{1}{(1-x)} = \sum_{n=0}^{\infty}x^n; \hspace{4pt} |x| \lt 1$$

## Function 2

Following the same process: 

$$f(x) = e^{x} = f'(x) = e^{n} = f^{n} = e^{x} \hspace{4pt} AND \hspace{4pt} f^{n}(0) = e^{0} = 1$$
Thus,our series looks like: 

$$1 + \frac{1}{1!}x + \frac{2}{2!}x^{2}+ \frac{3}{3!}x^{3} + \frac{4}{4!}x^{4} + \frac{5}{5!}x^{5}$$
Which could simply be written:

$$f(x) = e^{x} = \sum^{\infty}_{n = 0}\frac{x^{n}}{n!}$$
## Function 3 

Same method:

|Derivatives                            | Solved Maclaurin Series |
|---------------------------------------|-------------------------|
| $\ f(x) = ln(1+x)$                    |f(0) = 0                 |
|---------------------------------------|-------------------------|
| $\ f'(x) = \frac{1}{ln(1+x)}$         |f(0) = 1                 |
|---------------------------------------|-------------------------|
| $\ f''(x) = \frac{-1}{ln(1+x)^{2}}$   |f(0) = -1                |
|---------------------------------------|-------------------------|
| $\ f'''(x) = \frac{2}{ln(1+x)^{3}}$   |f(0) = 2                 | 
|---------------------------------------|-------------------------|
| $\ f^{4}(x) = \frac{-6}{ln(1+x)^{4}}$ |f(0) = -6                |
|---------------------------------------|-------------------------|
| $\ f^{5}(x) = \frac{24}{ln(1+x)^{5}}}$|f(0) = 24                |
|---------------------------------------|-------------------------|


In series we have: 

$$0 + \frac{1}{1!}(x) + \frac{-1}{2!}(x^{2}) + \frac{2}{3!}(x^{3}) + \frac{-6}{4!}(x^{4}) + \frac{24}{5!}(x^{5})$$
$$\ f(x) = x+ \frac{x^2}{2!}+\frac{x^3}{3!}+\frac{x^4}{4!}+\frac{x^5}{5!}$$
$$f(x) = ln(1+x) = \sum^{\infty}_{n = 0}\frac{x^n}{n!}$$




















