---
title: "Untitled"
author: "Jeyaraman Ramalingam"
date: "6/25/2021"
output:   
  html_document:
    toc: yes
    toc_depth: '4'
    df_print: paged
    toc_float: yes
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Input Dataset

```{r}
library(dplyr)
library(zoo)
library(xts)
library(forecast)
library(urca)
library(ROCR)
library(readxl)
library(TSstudio)
library(stringr)
library(kableExtra)

# setwd("C:/Users/Zachary.Palmore/GitHub/msds/Predictive Analytics/Projects/Project1")
df <- read_excel('Data Set for Class.xls')
head(df,5)
```

## Data Preparation

```{r pressure, echo=FALSE}
df <- readxl::read_excel('Data Set for Class.xls')
df$allDates <- as.Date(df$SeriesInd, origin = "1900-01-01")
allDates <- seq.Date(min(df$allDates),max(df$allDates),"day")
```

## Data Subsetting
```{r}
df_build<-function(grp,variable){
  final_df = subset(df[,c(1,2,variable,8)], is.na(group)==TRUE | group == grp)%>% .[,c(3,4)]%>% left_join(as.data.frame(allDates),.,by=c("allDates"= "allDates"))
  colnames(final_df)[1:2]<-c("allDates","Var")
  df_xts <- xts(c(final_df$Var),  order.by=as.Date(final_df$allDates))%>% na.approx()
  return(df_xts)  
}
```

## Models
```{r}
arima_model <- function(df_xts)
{
  df_xts_train <- window(df_xts,start="2011-05-08",end="2016-12-08")
  df_xts_test <- window(df_xts,start="2016-12-09",end="2018-05-03")
  aa_model <- auto.arima(log(df_xts_train))
  summary(aa_model)
  coef(aa_model)
  checkresiduals(aa_model)
  fc <- forecast(aa_model,h=511)
  fc$mean<-exp(fc$mean)
  fc$upper<-exp(fc$upper)
  fc$lower<-exp(fc$lower)
  fc$x<-exp(fc$x)
  
  return(fc)
}
```

## Accuracy
```{r}
plot_fc <- function(fc)
{
  return(autoplot(fc))
}
accuracy_test <- function(fc,df_xts)
{
  df_xts_train <- window(df_xts,start="2011-05-08",end="2016-12-08")
  df_xts_test <- window(df_xts,start="2016-12-09",end="2018-05-03")
  Mape_value<-accuracy(fc,df_xts_test)
  return(Mape_value)
}
```

### Forecasts
```{r}
list_group<- c("S04:3:4","S05:4:5","S06:5:7")
mape_df <- data.frame(matrix(ncol=3,nrow=3))
plt_list <- list()
k=1
for (i in 1:3)
{
  j=2
  grp_split<-unlist(str_split(list_group[i],":"))
  grp<-grp_split[[1]]
  var=list(grp_split[[2]],grp_split[[3]])
  mape_df[i,1]=grp
  for(item in var)
  {
    cat(paste("### Model for "," ",grp," ",item))
    df_xts<-df_build(grp,as.numeric(item))
    fc<-arima_model(df_xts)
    acc<-accuracy_test(fc,df_xts)
    mape_df[i,j]=acc[2,5]
    plt_list[[k]]<-plot_fc(fc)
    j=j+1
    k=k+1
    #write.csv(fc,file=paste0(grp,"_",item,".csv"))
  }  
}
```

### Mape Values

```{r}
colnames(mape_df)=c("Group","Var 1","Var 2")
knitr::kable(mape_df)%>%  kable_styling()
```

### Forecast Plots

```{r}
gridExtra::grid.arrange(grobs = plt_list)
```

